version: "3.5"

services:
  app:
    container_name: media_backend
    restart: always
    build: .
    ports: 
      - '80:3000'
    links: 
      - database
  
  database: 
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=media
    volumes:
      - ./pgdata:/var/lib/postgresql/data 
    ports:
      - '5433:5432'